#+AUTHOR: Christian Papilloud
#+LANGUAGE: de
#+OPTIONS: toc:nil num:nil H:4 ^:nil
#+STARTUP: showall
#+LATEX_CLASS: book
#+LATEX_CLASS_OPTIONS: [11pt,a4paper]
#+CITE_EXPORT: csl chicago-author-date-de-ibid.csl
#+BIBLIOGRAPHY: Bericht.bib


* Vorwort
:PROPERTIES:
:STATUS: DRAFT
:END:

Dieses Buch verlängert die Arbeiten, die zur Theorie der Relation als einem analytisch-interpretativen Rahmen im Zusammenhang der bestehenden relationalen Ansätze in der soziologischen Theorie geführt und diesen Rahmen in empirischen Untersuchungen verwendet haben. Es zieht die Folgen aus der Diskussion, die diese Arbeiten ausgelöst hat und die vor allem zwei Aspekte der Theorie der Relation betrifft.

Zum einen haben sich Fragen nach der inneren Kohärenz des theoretischen Rahmens gestellt. Diese Fragen sind legitim, weil die Theorie der Relation eine Fülle neuer Begriffe entwickelt, deren Verbindung untereinander für Soziologinnen und Soziologen nicht selbstverständlich ist, die mit einem solchen Rahmen nicht vertraut sind. Wir haben versucht, diese innere Kohärenz zu prüfen, indem wir die Theorie der Relation mit der Unterstützung von einer künstlichen Intelligenz in ein analytisches Modell umgewandelt haben, das sie simuliert und sich gegen ihre eigenen Annahmen und ihre Architektur testen lässt.

Zum zweiten und darauf aufbauend haben wir versucht, dieses Modell — den digitalen Zwilling der Theorie der Relation — dazu zu verwenden, die Theorie der Relation im Vergleich zu anderen Theorierahmen, die mehr oder weniger nach einem relationalen Ansatz argumentieren, sowie mit den bedeutsamen Tendenzen der gegenwärtigen relationalen Soziologie zu betrachten. Das Ziel dieses Vergleichs war mit der Frage verbunden, welche Position die Theorie der Relation gegenüber diesen Theorierahmen einnimmt und worin sie sich von ihnen unterscheidet.

Dies hat uns drittens zu der Frage geführt, was uns die Theorie der Relation zeigt, das wir mit anderen Theorierahmen nicht sehen würden. Eine solche Frage zu beantworten, entfernt uns vom Vergleich zwischen Theorierahmen und deren Annahmen und führt zur Anwendung des digitalen Zwillings auf reale Daten — also zu einer Verwendung, die nicht mehr nur der epistemologischen Analyse dient, sondern den digitalen Zwilling als methodologisches Werkzeug in der soziologischen Untersuchung erprobt. Um diesen Schritt zu machen, haben wir ein Beispiel aus der Forschung zur sozialen Mobilität von Mitgliedern der Arbeiterklasse in England vom späten 18. bis zur Mitte des 20. Jahrhunderts gewählt und es mit dem digitalen Zwilling behandelt.

Dieses Buch veröffentlicht die Ergebnisse zu jedem dieser drei Schritte. Es schlägt damit nicht nur ein Werkzeug für die Methodenentwicklung im Rahmen relationaler Ansätze vor, die mit der Theorie der Relation arbeiten möchten, sondern auch eine emergente Ebene aus einer Reihe von Vorarbeiten zur Theorie der Relation: Es vernetzt deren Ergebnisse stärker untereinander, vervollständigt sie und führt das damit verbundene Forschungsprogramm weiter.

Unser Dank geht an die Kolleginnen und Kollegen an unserem Institut, die sich mit unseren Texten auseinandergesetzt haben, sowie an die Gemeinschaft der relationalen Soziologinnen und Soziologen, mit der wir uns in den letzten Jahren intensiv ausgetauscht haben. Speziell gilt unser Dank Walter Bartl, Larissa Buchholz, Dominique Carré, Michel Grossetti, Reinhold Sackmann, Eva-Maria Schultze, Robert Seyfert, Frédéric Vandenberghe, Geneviève Vidal für ihre aufmerksame Lektüre und die anregenden Diskussionen der letzten Jahre.
